export const metadata = {
  title: "SpicyTube",
  description: "Generated by create next app",
};

export default function LayoutCategory({children,
}: {
  children: React.ReactNode;
}) {
  return <div className="w-full mx-auto">{children}</div>;
}
