export const metadata = {
  title: 'SpicyTube',
  description: 'Generated by create next app',
}

export default function LayoutInicio({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-full mx-auto'>{children}</body>
    </html>
  )
}