export const metadata = {
  title: "SpicyX",
  description: "Generated by create next app",
};

export default function LayoutSearch({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="w-full mx-auto">{children}</div>;
}
